-- SQLite
-- PRAGMA foreign_key_list(rapports_financiers);
-- PRAGMA table_info(rapports_financiers);
-- SELECT sql FROM sqlite_master WHERE type='table' AND name='rapports_financiers';
-- UPDATE taches SET statut = 'EN_ATTENTE' WHERE statut = 'En attente';
