"""reorganisation de la table Projet Taches

Revision ID: 0329ac676522
Revises: ce7fb0cd5e8e
Create Date: 2024-11-12 20:27:25.522322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0329ac676522'
down_revision = 'ce7fb0cd5e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rapports_financiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('budget_utilise', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('solde', sa.Float(), nullable=False))
        batch_op.drop_column('contenu')
        batch_op.drop_column('annee')

    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.drop_column('statut')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('rapports_financiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annee', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contenu', sa.TEXT(), nullable=True))
        batch_op.drop_column('solde')
        batch_op.drop_column('budget_utilise')
        batch_op.drop_column('budget_total')

    # ### end Alembic commands ###
