"""Ajout de la colonne date_occurrence à la table participations

Revision ID: 377a750bdea3
Revises: 5381f37da17f
Create Date: 2024-10-23 19:44:09.363935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a750bdea3'
down_revision = '5381f37da17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_occurrence', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('date_occurrence')

    # ### end Alembic commands ###
