"""unset role for MembreTache

Revision ID: 43630621677e
Revises: 6af499eaf1fd
Create Date: 2024-11-21 05:36:32.066559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43630621677e'
down_revision = '6af499eaf1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membre_taches', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membre_taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
