"""Ajout de la table HistoriqueStatut

Revision ID: 4d6958d9c1b9
Revises: f8711c88d237
Create Date: 2024-10-02 20:46:29.198916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6958d9c1b9'
down_revision = 'f8711c88d237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_statuts',
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.Column('statut_id', sa.Integer(), nullable=False),
    sa.Column('date_changement', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ),
    sa.ForeignKeyConstraint(['statut_id'], ['statuts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_statuts')
    # ### end Alembic commands ###
