"""ajoute de relation inscription_membre, inscription_evenement. Ajout du champ desctiption pour Evenement

Revision ID: 5381f37da17f
Revises: 4d6958d9c1b9
Create Date: 2024-10-18 02:52:49.469671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5381f37da17f'
down_revision = '4d6958d9c1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
