"""Set datedebut et date_fin to null true

Revision ID: 6af499eaf1fd
Revises: 143956a4b554
Create Date: 2024-11-19 00:29:59.209642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af499eaf1fd'
down_revision = '143956a4b554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.alter_column('date_debut',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('date_fin',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.alter_column('date_fin',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_debut',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
