"""suppression de clé primaire id de MembreTache pour clé primaire composite(membre_id, tache_id) 

Revision ID: cc045fc3c57c
Revises: d9c8ec2a661c
Create Date: 2024-12-07 11:25:56.140503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc045fc3c57c'
down_revision = 'd9c8ec2a661c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couts', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couts', schema=None) as batch_op:
        batch_op.alter_column('montant',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
