"""Ajouter de type_don, description à la class Don

Revision ID: ce7fb0cd5e8e
Revises: 377a750bdea3
Create Date: 2024-11-05 05:01:49.990877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7fb0cd5e8e'
down_revision = '377a750bdea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_don', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('montant', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('date_transaction', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.drop_column('date_transaction')
        batch_op.drop_column('montant')
        batch_op.drop_column('description')
        batch_op.drop_column('type_don')

    # ### end Alembic commands ###
