"""unset role and date_dasignation for MembreTache

Revision ID: f253a6bc7420
Revises: 43630621677e
Create Date: 2024-11-21 05:40:25.246617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f253a6bc7420'
down_revision = '43630621677e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membre_taches', schema=None) as batch_op:
        batch_op.drop_column('date_assignation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membre_taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_assignation', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
